### ISSUE TITLE
Append "_P" to all PAK file names if it isn't already present

### ISSUE THREAD

**Issue by Azekthi** [agc93/acevortex#3]
Mod files are normally incompatible with any aircraft that has an updated model or texture from the base game, or is a DLC aircraft. In order to solve this, `.pak` instead needs to be `_P.pak`

Some mod authors have updated their mods accordingly, and most newer mods take this into account, but older mod files do not have this filename suffix ([here's an example](https://www.nexusmods.com/acecombat7skiesunknown/mods/122)), and they remain broken as a result. In addition, if any of the current aircraft are updated in the future, all of that aircraft's mods will instantly stop working unless they are renamed.

In order to solve this, users must rename the files accordingly, but this is not something they should be doing with Vortex. Instead, this extension should install _all_ mod files by replacing `.pak` with `_P.pak` if the mod file doesn't already end in `_P.pak` to ensure every mod works.

**Comment by agc93** [comment]
Thanks for the suggestion @Azekthi ! That definitely seems like it should be easy enough to implement. I'll do some testing to make sure that doesn't break anything and it should make it into the next release 👍

**Comment by agc93** [comment]
@Azekthi I've just published 0.1.4 of the extension that includes this feature. It's live on Nexus Mods now, so give it a day or two to make it to Vortex and files should be renamed on installation.

This won't apply retroactively though, so you will need to reinstall any affected mods. Thanks again for the suggestion!

**Comment by Azekthi** [comment]
This is not working with single-pak files, ones that don't require the special installation process.

**Comment by agc93** [comment]
Shit, you're right. Thanks for spotting that @Azekthi, I'll fix that up

**Comment by agc93** [comment]
@Azekthi v0.1.5 has been uploaded now with this fixed (hopefully properly this time).

Give it a day or two to make it to Vortex and let me know if it's still not working right. Thanks again for reporting this!
