### ISSUE TITLE
Vortex isn't seeing release 0.2.0 on Nexus

### ISSUE THREAD

**Issue by Azekthi** [agc93/acevortex#5]
I'm not sure what's going on, but Vortex isn't recognizing the release of 0.2.0 from the Nexus site. The extensions pane only sees 0.1.5 and isn't finding any updates. I could install 0.2.0 manually, but I'm not sure if that might screw something up.

I should mention that Vortex doesn't load the extension in `%APPDATA%\Vortex\plugins\game-acecombat7skiesunknown` instead the folder is `%APPDATA%\Vortex\plugins\AC7 Support for Vortex-125-0-1-5-1599583613` I don't know if that might have something to do with it?

**Comment by agc93** [comment]
Vortex will only load updates once they've been added to a special file in the Vortex repo that it reads for available updates.

You should be seeing the update available now. If you manually install it (aka into `%APPDATA%\Vortex\plugins\game-acecombat7skiesunknown` Vortex unfortunately won't auto-update it).

**Comment by Azekthi** [comment]
That's... really annoying. They're taking feedback for Vortex updates, I may bring that up because it should just check Nexus itself, not some special file in a repo. Thanks for the help!

**Comment by agc93** [comment]
Just to give you a heads up, I've raised this before with them and they've indicated that this is the approach they're sticking to. They have their reasons and as much as it's irritating (especially for someone in my position) it's also reasonably integral to Vortex's current extensibility model.

I definitely agree, but just don't get your hopes up too high on that changing :)
