### ISSUE TITLE
Skins not being detected

### ISSUE THREAD

**Issue by Azekthi** [agc93/acevortex#6]
Reports below:

https://privatebin.nexusmods.com/?0b1922a591fba93b#8uybQiBPdrbqQBGrLUNRQTBy9nrpiGRmuwZALyhwizRL

https://privatebin.nexusmods.com/?2b245451ae78b8f2#rJj5TaY3yzttPR62aDoqMucXZ9bMvR2AzzBJSanc7yZ

https://privatebin.nexusmods.com/?b9bc56dffe008ab4#AQLf7qvQY3WVXFdQa87DpkQLDwCmUVSjQFnByaune74A

**Comment by agc93** [comment]
Just to let you know, I can replicate this now (I was installing different files) and I *think* I have a fix for it, but need to do some more testing.

**Comment by agc93** [comment]
I overhauled how the detection works again in 0.3.0, so we should be detecting those (and a few of the other edge cases more reliably now). Going to close this now, let me know if you see more that aren't picked up properly.

**Comment by Azekthi** [comment]
I saw, and thank you! Only two skins are not being detected now:

https://www.nexusmods.com/acecombat7skiesunknown/mods/476

https://www.nexusmods.com/acecombat7skiesunknown/mods/932 -- This one _may_ be because it uses a different loading method. I'm using the "Experimental" version.

**Comment by agc93** [comment]
Yep, because of how light weight packing works, I don't think I'll be able to support detection for them, likely ever.

As for that MTD skin, yeah I have no f'ing idea how that was packed and it's the only one I've seen like that. Nothing I can do for that one either, unfortunately.

**Comment by Azekthi** [comment]
Haha, no worries, thank you for all your work 👍
